#!/bin/bash

if [[ "$@" == *"--query-only"* ]]; then
    echo "PSQL: {$@}"
    exit
fi

if [[ -z "${PSQL}" ]]; then
    PSQL=/usr/bin/psql
fi

source $(dirname "$0")/_load_pg_props.sh

${PSQL} --dbname=${DB_DATABASE} --username=${DB_USER} --host=${DB_HOST} --port=${DB_PORT} "$@"
