#!/usr/bin/env bash

if [[ "$@" == *"--query-only"* ]]; then
    echo "PSQL: {$@}"
    exit
fi

if [[ -z "${PSQL}" ]]; then
    # PSQL="docker exec -it postgres psql"
    PSQL="/usr/bin/psql"
fi

source $(dirname "$0")/_load_pg_props.sh

${PSQL} --dbname=${DB_DATABASE} --username=${DB_USER} --host=${DB_HOST} --port=${DB_PORT} "$@"
#echo "${PSQL} --dbname=${DB_DATABASE} --username=${DB_USER} --host=${DB_HOST} --port=${DB_PORT}"
